package gouno

import (
	"log"

	"github.com/rushairer/gouno/generator"
	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
	Use:   "gouno",
	Short: "gouno project command",
	Long:  "Project-aware command host generated by gouno.",
	CompletionOptions: cobra.CompletionOptions{
		DisableDefaultCmd: true,
	},
}

func init() {
	rootCmd.AddCommand(webCmd)
}

func Execute() {
	if _, err := generator.AttachProjectCommand(rootCmd, ""); err != nil {
		log.Fatalf("load project commands: %v", err)
	}
	if err := rootCmd.Execute(); err != nil {
		log.Fatalf("Error executing root command: %v", err)
	}
}
