name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: gouno-template-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    uses: rushairer/gouno-doc/.github/workflows/project-template-quality.yml@52147af0736efcc892422000f9369b331392c5c4 # gouno-doc v1.2.0
  conventional-pr:
    uses: rushairer/gouno-doc/.github/workflows/conventional-pr.yml@52147af0736efcc892422000f9369b331392c5c4 # gouno-doc v1.2.0
